---
# Test creating a file
- name: Ensure test file
  hosts: all
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: /tmp/testfile.txt
# Create a user
- name: Ensure HelloDojo user
  hosts: all
  tasks:
   - user:
      name: HelloDojo
      comment: Hello Dojo
      group: dojo
  become: yes
