---
- name: Install docker Package
  apt:
    name: docker.io
    state: present
  become: yes
  tags:
    - install-docker

- name: Start service docker, if not started
  service:
    name: docker
    state: started
  become: yes

- name: Ensure dojo user in docker group
  user:
    name: dojo
    append: yes
    groups: docker
    state: present
  become: yes

- name: Ensure pi user in docker group
  user:
    name: pi
    append: yes
    groups: docker
    state: present
  become: yes

- name: Install python-backports.ssl-match-hostname package
  apt:
    name: python-backports.ssl-match-hostname
    state: present
  become: yes

- name: Remove pip docker
  pip:
    name: docker
    state: absent
  become: yes

- name: Remove pip docker-py
  pip:
    name: docker-py
    state: absent
  become: yes

- name: Install docker for pip
  pip:
    name: docker
    state: present
  become: yes

- name: Create a web directory in dojo's home
  file:
    path: /home/dojo/web
    state: directory

- name: Deploy inline template
  copy:
    content: '<html><head><title>Hello</title></head><body><h1>Hello World!</h1></body></html>'
    dest: /home/dojo/web/index.html

- name: Test docker
  docker_container:
    name: test-apache-hello-world
    state: started
    image: httpd:2.4
    volumes:
      - /home/dojo/web:/usr/local/apache2/htdocs/
    ports:
      - "8181:80"
  
